global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['back:8080']  # или порт, где твой сервис отдает метрики
    metrics_path: '/metrics'     # стандартный путь для метрик
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']